### PR TITLE
Added missing PaymentTransactionCodeTypes. "refund", "reversal"

### PR DESCRIPTION
**Pull request by Grizaster**

### CODE REVIEW

**Comment by pp-randy** [comment]
Can you provide an example of the XML where you saw `reversal` in PaymentTransactionCodeType?  

I don't see`reversal` in [eBLBaseComponents.xsd](https://www.paypalobjects.com/wsdl/eBLBaseComponents.xsd).

**Comment by thoemy** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cc="urn:ebay:apis:CoreComponentTypes" xmlns:wsu="http://schemas.xmlsoap.org/ws/2002/07/utility" xmlns:saml="urn:oasis:names:tc:SAML:1.0:assertion" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:ed="urn:ebay:apis:EnhancedDataTypes" xmlns:ebl="urn:ebay:apis:eBLBaseComponents" xmlns:ns="urn:ebay:api:PayPalAPI">
	<SOAP-ENV:Header>
		<Security xmlns="http://schemas.xmlsoap.org/ws/2002/12/secext" xsi:type="wsse:SecurityType"/>
		<RequesterCredentials xmlns="urn:ebay:api:PayPalAPI" xsi:type="ebl:CustomSecurityHeaderType">
			<Credentials xmlns="urn:ebay:apis:eBLBaseComponents" xsi:type="ebl:UserIdPasswordType"/>
		</RequesterCredentials>
	</SOAP-ENV:Header>
	<SOAP-ENV:Body id="_0">
		<TransactionSearchResponse xmlns="urn:ebay:api:PayPalAPI">
			<Timestamp xmlns="urn:ebay:apis:eBLBaseComponents">2017-07-04T08:56:47Z</Timestamp>
			<Ack xmlns="urn:ebay:apis:eBLBaseComponents">Success</Ack>
			<CorrelationID xmlns="urn:ebay:apis:eBLBaseComponents">c6d9b029a7e1e</CorrelationID>
			<Version xmlns="urn:ebay:apis:eBLBaseComponents">204.0</Version>
			<Build xmlns="urn:ebay:apis:eBLBaseComponents">29297572</Build>
			<PaymentTransactions xmlns="urn:ebay:apis:eBLBaseComponents" xsi:type="ebl:PaymentTransactionSearchResultType">
				<Timestamp xsi:type="xs:dateTime">2015-08-24T14:42:57Z</Timestamp>
				<Timezone xsi:type="xs:string">GMT</Timezone>
				<Type xsi:type="xs:string">Reversal</Type>
				<Payer xsi:type="ebl:EmailAddressType"/>
				<PayerDisplayName xsi:type="xs:string">REMOVED</PayerDisplayName>
				<TransactionID>REMOVED</TransactionID>
				<Status xsi:type="xs:string">Completed</Status>
				<GrossAmount xsi:type="cc:BasicAmountType" currencyID="EUR">-39.40</GrossAmount>
				<FeeAmount xsi:type="cc:BasicAmountType" currencyID="EUR">0.94</FeeAmount>
				<NetAmount xsi:type="cc:BasicAmountType" currencyID="EUR">-38.46</NetAmount>
			</PaymentTransactions>
		</TransactionSearchResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cc="urn:ebay:apis:CoreComponentTypes" xmlns:wsu="http://schemas.xmlsoap.org/ws/2002/07/utility" xmlns:saml="urn:oasis:names:tc:SAML:1.0:assertion" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:ed="urn:ebay:apis:EnhancedDataTypes" xmlns:ebl="urn:ebay:apis:eBLBaseComponents" xmlns:ns="urn:ebay:api:PayPalAPI">
	<SOAP-ENV:Header>
		<Security xmlns="http://schemas.xmlsoap.org/ws/2002/12/secext" xsi:type="wsse:SecurityType"/>
		<RequesterCredentials xmlns="urn:ebay:api:PayPalAPI" xsi:type="ebl:CustomSecurityHeaderType">
			<Credentials xmlns="urn:ebay:apis:eBLBaseComponents" xsi:type="ebl:UserIdPasswordType"/>
		</RequesterCredentials>
	</SOAP-ENV:Header>
	<SOAP-ENV:Body id="_0">
		<GetTransactionDetailsResponse xmlns="urn:ebay:api:PayPalAPI">
			<Timestamp xmlns="urn:ebay:apis:eBLBaseComponents">2017-07-04T09:00:38Z</Timestamp>
			<Ack xmlns="urn:ebay:apis:eBLBaseComponents">Success</Ack>
			<CorrelationID xmlns="urn:ebay:apis:eBLBaseComponents">9605054de3633</CorrelationID>
			<Version xmlns="urn:ebay:apis:eBLBaseComponents">204.0</Version>
			<Build xmlns="urn:ebay:apis:eBLBaseComponents">29297572</Build>
			<PaymentTransactionDetails xmlns="urn:ebay:apis:eBLBaseComponents" xsi:type="ebl:PaymentTransactionType">
				<ReceiverInfo xsi:type="ebl:ReceiverInfoType">
					<Business xsi:type="ebl:EmailAddressType"/>
					<Receiver xsi:type="ebl:EmailAddressType"></Receiver>
					<ReceiverID xsi:type="ebl:UserIDType"></ReceiverID>
				</ReceiverInfo>
				<PayerInfo xsi:type="ebl:PayerInfoType">
					...
				</PayerInfo>
				<TPLReferenceID xsi:type="xs:string"/>
				<PaymentInfo xsi:type="ebl:PaymentInfoType">
					<TransactionID>REMOVED</TransactionID>
					<ParentTransactionID xsi:type="ebl:TransactionId">REMOVED</ParentTransactionID>
					<ReceiptID/>
					<TransactionType xsi:type="ebl:PaymentTransactionCodeType">reversal</TransactionType>
					<PaymentType xsi:type="ebl:PaymentCodeType">instant</PaymentType>
					<PaymentDate xsi:type="xs:dateTime">2015-08-24T14:42:57Z</PaymentDate>
					<GrossAmount xsi:type="cc:BasicAmountType" currencyID="EUR">-39.40</GrossAmount>
					<TaxAmount xsi:type="cc:BasicAmountType" currencyID="EUR">0.00</TaxAmount>
					<ExchangeRate xsi:type="xs:string"/>
					<PaymentStatus xsi:type="ebl:PaymentStatusCodeType">Completed</PaymentStatus>
					<PendingReason xsi:type="ebl:PendingStatusCodeType">none</PendingReason>
					<ReasonCode xsi:type="ebl:ReversalReasonCodeType">none</ReasonCode>
					<ShippingMethod xsi:type="xs:string">Standard</ShippingMethod>
					<ProtectionEligibility xsi:type="xs:string">Ineligible</ProtectionEligibility>
					<ProtectionEligibilityType xsi:type="xs:string">None</ProtectionEligibilityType>
					<ShipAmount xsi:type="xs:string"/>
					<ShipHandleAmount xsi:type="xs:string"/>
					<ShipDiscount xsi:type="xs:string"/>
					<InsuranceAmount xsi:type="xs:string">0.00</InsuranceAmount>
					<Subject xsi:type="xs:string"/>
					<ReceiptReferenceNumber xsi:type="xs:string"/>
					<POSTransactionType xsi:type="xs:string"/>
					<StoreID xsi:type="xs:string"/>
					<TerminalID xsi:type="xs:string"/>
					<BinEligibility xsi:type="xs:string"/>
				</PaymentInfo>
				<PaymentItemInfo xsi:type="ebl:PaymentItemInfoType">
					...
				</PaymentItemInfo>
				<OfferCouponInfo xsi:type="ebl:OfferCouponInfoType">
					<Type xsi:type="xs:string"/>
					<ID xsi:type="xs:string"/>
					<Amount xsi:type="xs:string"/>
					<AmountCurrency xsi:type="xs:string"/>
				</OfferCouponInfo>
				<GiftReceipt xsi:type="xs:string">0</GiftReceipt>
			</PaymentTransactionDetails>
		</GetTransactionDetailsResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Comment by Grizaster** [comment]
Thank you @thoemy to post an example!

**Comment by pp-randy** [comment]
Looks good to me

**Pull request merged**
